name: sobo_flutter
description: Simple yet robust & reactive note-taking app made with flutter, rxdart, and hive.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  hive_flutter: ^1.1.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
